apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waypoint-storage-claim
  namespace: waypoint
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
