apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: default-backend
