apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: waypointhttp
      port: 9701
      targetPort: 9701
      protocol: TCP
    - name: waypointgrpc
      port: 9702
      targetPort: 9702
      protocol: TCP
  selector:
    app: nginx-ingress-controller
